# Lucho's showers

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
file_path = '..\SWGO_SCRIPTS\data_hornita.csv'
df=pd.read_csv(file_path,delimiter = ",")
nan_counts = df.isna().sum()
print(nan_counts)
# Drop rows with NaN values in-place
df.dropna(inplace=True)


x                        0
y                        0
z                        0
Detected_Energy          0
Shower_Initial_Energy    0
dtype: int64


In [3]:
df
matrix = df.values
matrix

array([[ 5.69411232e+01,  1.33848104e+02,  6.00000000e-02,
         3.47000000e+00,  2.24362150e+04],
       [ 1.62688924e+01,  9.15802815e+01,  6.00000000e-02,
         3.37000000e+00,  2.24362150e+04],
       [ 1.62688924e+01,  9.15802815e+01,  6.00000000e-02,
         3.28000000e+00,  2.24362150e+04],
       ...,
       [-2.23697270e+01,  8.10133259e+01,  6.00000000e-02,
         3.41000000e+00,  1.32185688e+05],
       [-2.64369501e+01,  8.10133259e+01,  6.00000000e-02,
         3.42000000e+00,  1.32185688e+05],
       [-2.23697270e+01,  8.10133259e+01,  6.00000000e-02,
         2.31000000e+00,  1.32185688e+05]])

In [4]:
df

x           y     z  Detected_Energy  Shower_Initial_Energy
0          56.941123  133.848104  0.06             3.47             22436.2150
1          16.268892   91.580281  0.06             3.37             22436.2150
2          16.268892   91.580281  0.06             3.28             22436.2150
3          16.268892   91.580281  0.06             2.69             22436.2150
4          16.268892   91.580281  0.06             2.69             22436.2150
...              ...         ...   ...              ...                    ...
108534437  -8.134446 -295.874755  0.07             2.67            132185.6884
108534438  -8.134446 -295.874755  0.07             4.07            132185.6884
108534439 -22.369727   81.013326  0.06             3.41            132185.6884
108534440 -26.436950   81.013326  0.06             3.42            132185.6884
108534441 -22.369727   81.013326  0.06             2.31            132185.6884

[108534442 rows x 5 columns]

In [5]:
df2 =df[['x', 'y','Detected_Energy','Shower_Initial_Energy']]

In [6]:
matrix = df2.values
matrix

array([[ 5.69411232e+01,  1.33848104e+02,  3.47000000e+00,
         2.24362150e+04],
       [ 1.62688924e+01,  9.15802815e+01,  3.37000000e+00,
         2.24362150e+04],
       [ 1.62688924e+01,  9.15802815e+01,  3.28000000e+00,
         2.24362150e+04],
       ...,
       [-2.23697270e+01,  8.10133259e+01,  3.41000000e+00,
         1.32185688e+05],
       [-2.64369501e+01,  8.10133259e+01,  3.42000000e+00,
         1.32185688e+05],
       [-2.23697270e+01,  8.10133259e+01,  2.31000000e+00,
         1.32185688e+05]])

In [7]:
unique_numbers = df['Shower_Initial_Energy'].unique()

# Create a dictionary to store matrices for each unique number
matrices = {}

# Loop through unique numbers and create matrices
for number in unique_numbers:
    subset_df = df[df['Shower_Initial_Energy'] == number]
    matrices[number] = subset_df[['x', 'y','Detected_Energy']].values

In [8]:
unique_numbers

array([ 22436.215 ,  14222.6374,  12838.0746, ...,  15728.3999,
        10084.7814, 132185.6884])

In [17]:
%run test2.py

In [12]:
unique_numbers[2]

12838.074600000002

In [18]:
q = 1
for i in unique_numbers:
    shower100(matrices[i],q,'images')
    shower600(matrices[i],q,'images')
    if abs(i -unique_numbers[5]) < 0.001:
        break
    q = q+1
        

In [ ]:
shower100(matrix,1)

In [ ]:
shower600(matrix,1,1000)

In [ ]:
# Create an empty list to store DataFrames
dataframes = []

# Loop through numbers from 1 to 100
for i in range(1, 100):
    # Generate the file name for each iteration
    file_name = f'..\csv\Matrix_Horna\matrix{i}_1000GeV.csv'
    df = pd.read_csv(file_name)
    df2 =df[['x', 'y','energy_shower']]
    matrix = df2.values
    shower600(matrix,i,1000)

# Now, 'dataframes' is a list containing 1000 DataFrames, each representing a CSV file


In [ ]:
dataframes[1]